apiVersion: apps/v1              #Replicaset 
kind: ReplicaSet
metadata:
  name: my-rs
spec: 
  replicas: 3
  selector:
    matchExpressions:
      - key: "app"
        operator: "In"
        values: ["xyz-app", "cbz-app"]
  template: 
    metadata: 
      labels:
        app: cbz-app 
    spec:
      containers:
      - name: my-pod-container 
        image: nginx
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
---
apiVersion: v1         #nodeport  service 
kind: Service 
metadata: 
  name: my-svc
spec: 
  selector: 
    app: cbz-app 
  ports: 
  - name: http 
    targetPort: 80 
    port: 80 
  type: NodePort


